### ISSUE TITLE
无法输入中文

### ISSUE THREAD

**Issue by lyj88a** [Cool-Pan/fcitx-rime-flypy#1]
执行命令后，rime可以选择方案，但是无法输入中文。fcitx是可以正常使用的。

**Comment by rooleongai** [comment]
我也遇到了这样的情况，今天我打开WPS发现可以调用fcitx但是无法输上中文，只能输上英文。

我电脑环境是archlinux+kde，fcitx在终端在火狐和谷歌浏览器在openoffice等软件中都可以正常输入中文，唯独在WPS中无法输入中文。

现在还不知道如何解决。

**Comment by Cool-Pan** [comment]
@yooleongai 
如果 fcitx 在部分軟件中能輸入中文而部分軟件中不能輸入中文，考慮是否安裝相應的模塊。
可嘗試 ``sudo pacman -S fcitx-im``

**Comment by Cool-Pan** [comment]
@lyj88a 
如果 fcitx 能正常使用，而 rime 無法輸入中文，考慮 rime 是否配置正確。

不知你使用的哪個 rime 方案。這個倉庫的 rime 方案是根據 flypy 官網的文件微調而來的，也經過我的測試，並且默認只能輸入中文，應該是沒有問題的。
